from __future__ import annotations

from pathlib import Path

import streamlit as st

from web.dashboard_data import DashboardData, DashboardTask, TimelineEvent, load_dashboard_data


def render_dashboard(default_results_path: Path) -> None:
    st.title("Trace/Eval Dashboard")

    results_path = Path(st.text_input(
        "Eval results file",
        value=str(default_results_path),
        help="Path to eval_results.json generated by sca-eval run.",
    ))

    if not results_path.is_file():
        st.info("Run `sca-eval run --model <model>` or point this dashboard at an existing eval_results.json.")
        return

    try:
        data = load_dashboard_data(results_path)
    except Exception as exc:
        st.error(f"Unable to load dashboard data: {exc}")
        return

    _render_summary(data)
    left, middle, right = st.columns([1.1, 1.6, 1.4], gap="medium")

    with left:
        task = _render_task_list(data)

    if task is None:
        middle.info("Select an eval task.")
        return

    with middle:
        _render_timeline(task)

    with right:
        _render_task_details(task)


def _render_summary(data: DashboardData) -> None:
    summary = data.summary
    cols = st.columns(5)
    cols[0].metric("Pass rate", f"{summary.pass_rate:.1%}", f"{summary.passed}/{summary.total}")
    cols[1].metric("Duration", f"{summary.total_duration_ms / 1000:.1f}s")
    cols[2].metric("Tool calls", str(summary.total_tool_calls))
    cols[3].metric("Failed tools", str(summary.failed_tool_calls))
    cols[4].metric("Tokens", f"{summary.total_tokens:,}")


def _render_task_list(data: DashboardData) -> DashboardTask | None:
    st.subheader("Tasks")
    if not data.tasks:
        st.caption("No eval tasks found.")
        return None

    options = [task.task_id for task in data.tasks]
    selected_id = st.radio(
        "Task",
        options,
        format_func=lambda task_id: _task_label(next(t for t in data.tasks if t.task_id == task_id)),
        label_visibility="collapsed",
    )
    return next(task for task in data.tasks if task.task_id == selected_id)


def _render_timeline(task: DashboardTask) -> None:
    st.subheader("Trace Timeline")
    if not task.timeline:
        st.info("No trace records found for this task.")
        st.caption(str(task.trace_path))
        return

    for event in task.timeline:
        _render_timeline_event(event)


def _render_timeline_event(event: TimelineEvent) -> None:
    status = _event_status(event)
    elapsed = f" · {event.elapsed_ms} ms" if event.elapsed_ms is not None else ""
    with st.expander(f"{status} {event.label}{elapsed}", expanded=event.type in {"error", "runner_error"}):
        if event.content:
            language = "json" if event.type in {"task_assessment", "tool_call", "token_stats"} else "text"
            st.code(_truncate(event.content), language=language)
        else:
            st.caption("No content")


def _render_task_details(task: DashboardTask) -> None:
    st.subheader("Task Detail")
    status = "PASS" if task.passed else "FAIL"
    st.caption(f"{status} · {task.duration_ms} ms · tools={task.tool_calls} · tokens={task.total_tokens:,}")

    tabs = st.tabs(["Report", "Diffs", "Failures", "Final Output"])
    with tabs[0]:
        if task.report_text:
            st.markdown(task.report_text)
        else:
            st.info("No final report found.")
            st.caption(str(task.report_path))

    with tabs[1]:
        if not task.patch_artifacts:
            st.info("No Actor patch artifacts found.")
        for patch_path in task.patch_artifacts:
            with st.expander(patch_path.name, expanded=False):
                st.code(_truncate(patch_path.read_text(encoding="utf-8", errors="replace"), 20000), language="diff")

    with tabs[2]:
        if task.failures:
            for failure in task.failures:
                st.error(failure)
        else:
            st.success("No eval failures recorded.")

    with tabs[3]:
        if task.final_output:
            st.markdown(task.final_output)
        else:
            st.caption("No final output captured.")


def _task_label(task: DashboardTask) -> str:
    prefix = "PASS" if task.passed else "FAIL"
    return f"{prefix} · {task.task_id}"


def _event_status(event: TimelineEvent) -> str:
    if event.type in {"error", "runner_error"} or event.success is False:
        return "FAIL"
    if event.type == "done" or event.success is True:
        return "OK"
    return "INFO"


def _truncate(text: str, max_chars: int = 8000) -> str:
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n\n... [truncated for dashboard display] ..."
